services:
  api-service:
    build: ./api-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - STOCKAGE_URL=${STOCKAGE_URL}
    depends_on:
      - db
    networks:
      - emojihub

  stockage-service:
    build: ./stockage-service
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy 
    networks:
      - emojihub
    env_file:
      - .env

  analyse-service:
    build: ./analyse-service
    depends_on:
      - db
    networks:
      - emojihub

  db:
    image: postgres:15
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - emojihub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emoji"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  emojihub:

volumes:
  pgdata: